# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qriif' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for qriif
  pod 'QRCodeReaderViewController', '~> 4.0.2'

end
